# Predicting Churn

### *1. Importing libraries and data*

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import tensorflow as tf
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/2.\ Career\ Development/Data\ Science/4.\ Data\ Science\ Projects/Predicting\ Churn/

Mounted at /content/drive
/content/drive/My Drive/2. Career Development/Data Science/4. Data Science Projects/Predicting Churn


In [ ]:
cols = ['Unnamed: 0', 'churn']
x = pd.read_csv('predicting_churn.csv').drop(cols, axis = 1)

In [ ]:
y = pd.read_csv('predicting_churn.csv')['churn']

__________________

### *2. Splitting Data into Training & Test Set*

**2.1 Scaled**

In [ ]:
y = y.values
x = x.values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

______________

### *3. Fitting a Decision Tree*

In [ ]:
decision_tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
decision_tree.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

Cross Validation Training Set

In [ ]:
accuracies = cross_val_score(estimator = decision_tree, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 91.97 %
Standard Deviation: 1.69 %


Test Set Performance

In [ ]:
y_pred = decision_tree.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[697  38]
 [ 31  84]]


0.9188235294117647

___________________________

### *4. Fitting KNN*

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski', p=2)
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

Cross Validation Training Set

In [ ]:
accuracies = cross_val_score(estimator = knn, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 88.71 %
Standard Deviation: 0.93 %


Test Set Performance

In [ ]:
y_pred = knn.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[731   4]
 [ 86  29]]


0.8941176470588236

____________

### *5. Logistic Regression*

In [ ]:
logistic_regression = LogisticRegression(random_state = 0)
logistic_regression.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Cross Validation Training Set

In [ ]:
accuracies = cross_val_score(estimator = logistic_regression, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 86.59 %
Standard Deviation: 0.95 %


Test Set Performance

In [ ]:
y_pred = logistic_regression.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[718  17]
 [ 92  23]]


0.8717647058823529

__________

### *6. Naive Bayes*

In [ ]:
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

Cross Validation Training Set

In [ ]:
accuracies = cross_val_score(estimator = nb, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 61.15 %
Standard Deviation: 3.29 %


Test Set Performance

In [ ]:
y_pred = nb.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[482 253]
 [ 52  63]]


0.6411764705882353

__________________

### *7. Random Forest*

In [ ]:
random_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
random_forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

Cross Validation Training Set

In [ ]:
accuracies = cross_val_score(estimator = random_forest, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 93.50 %
Standard Deviation: 0.99 %


Test Set Performance

In [ ]:
y_pred = random_forest.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[733   2]
 [ 47  68]]


0.9423529411764706

_____________________

### *8. SVM*

In [ ]:
svc = SVC(kernel = 'linear', random_state = 0)
svc.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

Cross Validation Training Set

In [ ]:
accuracies = cross_val_score(estimator = svc, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 85.79 %
Standard Deviation: 0.13 %


Test Set Performance

In [ ]:
y_pred = svc.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[735   0]
 [115   0]]


0.8647058823529412

___________________

### *9. Kernel SVM*

In [ ]:
kernel_svc = SVC(kernel = 'rbf', random_state = 0)
kernel_svc.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

Cross Validation Training Set

In [ ]:
accuracies = cross_val_score(estimator = kernel_svc, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 90.94 %
Standard Deviation: 0.76 %


Test Set Performance

In [ ]:
y_pred = kernel_svc.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[732   3]
 [ 58  57]]


0.928235294117647

_____________________

### *10. ANN*

In [ ]:
ann = tf.keras.models.Sequential()
#adding input layer and hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
#compiling the ann
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
#Training ANN
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
107/107 [==============================] - 1s 1ms/step - loss: 0.5759 - accuracy: 0.7947
Epoch 2/100
107/107 [==============================] - 0s 1ms/step - loss: 0.4273 - accuracy: 0.8440
Epoch 3/100
107/107 [==============================] - 0s 1ms/step - loss: 0.3743 - accuracy: 0.8486
Epoch 4/100
107/107 [==============================] - 0s 1ms/step - loss: 0.3386 - accuracy: 0.8591
Epoch 5/100
107/107 [==============================] - 0s 1ms/step - loss: 0.3214 - accuracy: 0.8598
Epoch 6/100
107/107 [==============================] - 0s 1ms/step - loss: 0.2900 - accuracy: 0.8652
Epoch 7/100
107/107 [==============================] - 0s 1ms/step - loss: 0.2917 - accuracy: 0.8724
Epoch 8/100
107/107 [==============================] - 0s 1ms/step - loss: 0.2533 - accuracy: 0.8986
Epoch 9/100
107/107 [==============================] - 0s 1ms/step - loss: 0.2411 - accuracy: 0.9097
Epoch 10/100
107/107 [==============================] - 0s 1ms/step - loss: 0.2516 - accura

Test Set Performance

In [ ]:
y_pred = (ann.predict(x_test) > 0.5).astype(int)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[714  21]
 [ 37  78]]


0.9317647058823529